# Generated by Django 3.2.4 on 2022-02-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.TextField()),
                ('country', models.TextField()),
                ('looks', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Could be Better'), (4, 'Alright'), (5, 'Good'), (6, 'Very Good'), (7, 'Incredible')])),
                ('accessibility', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Could be Better'), (4, 'Alright'), (5, 'Good'), (6, 'Very Good'), (7, 'Incredible')])),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Could be Better'), (4, 'Alright'), (5, 'Good'), (6, 'Very Good'), (7, 'Incredible')])),
                ('future_use', models.BooleanField()),
                ('recommend', models.BooleanField()),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name': 'feedback form',
                'verbose_name_plural': 'feedback forms',
            },
        ),
    ]
