# Generated by Django 3.2.4 on 2022-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='edit_admins_permission',
            field=models.BooleanField(default=False),
        ),
    ]
